### ISSUE TITLE
Support session with relative paths or point track location.

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/jbr#134]
At the moment session has hardcoded full paths and it make local session hard to share. We could improve this using 2 approaches:
* Save relative paths, e.g. relatively to a session file location.
  *  In some complex file layouts, when not all tracks are close to the session file user could use symlink in working directory as a workaround.
* For missing paths use Lightroom like behavior for handling bulk moved photos:
   * User provides source location for any track with missing file
   * JBR scans the folder and automatically matches other tracks with missing files according to the folder content. It will help to fix large sessions with simple path naming conventions if large track groups were moved to some other places.

P.S: IGV already supports some relative paths, so we could fix export to IGV also

**Comment by iromeo** [comment]
@dievsky 

1. I meant just to give a session file that could be opened successfully if user have track files with same relative paths. E.g. give user a `*.tar.gz` with session and track. It is similar to our sessions based on URLs, but no need to host all files in WEB. 

2. But here we could go further and allow to export a full session from jbr, i.e. a `*.tar.gz` archive with session file and track files. So users could just open such session in the browser.

To my mind `1.` is good to have, as for `2.` not sure, it is just like `syntax sugar` and true bioinformaticians likely want to separate data from 3rd party browser session descriptiors.

**Comment by dievsky** [comment]
Ah, now I get it. Very nice indeed.

**Comment by receed** [comment]
Handling missing paths is moved to #148.

**Comment by olegs** [comment]
Support sessions with relative genome paths was successfully implemented in https://github.com/JetBrains-Research/epigenome/commit/961965028cac0026f2373d27a95b1f3a4bf15dda
