### ISSUE TITLE
Support locating missing paths from session

### ISSUE THREAD

**Issue by receed** [JetBrains-Research/jbr#148]
At the moment trying to load missing file when opening a session causes an error. A possible workaround is:
* User provides source location for any track with missing file
* JBR scans the folder and automatically matches other tracks with missing files according to the folder content. It will help to fix large sessions with simple path naming conventions if large track groups were moved to some other places.

Moved from #134.

**Comment by olegs** [comment]
Implemented in PR https://github.com/JetBrains-Research/epigenome/pull/1453
