### ISSUE TITLE
Make "all supported file types" a default selection when opening files

### ISSUE THREAD

**Issue by dievsky** [JetBrains-Research/jbr#16]
When I try to open e.g. a bigWig file, I choose the "Load BigWig / Wig / BigBed File" action and see that my bigWig directory is empty. Then I realize that the file open dialog is set to show bigBed files, and I must change it manually to show bigWigs.

It's even worse with the Open Session dialog, since the default here is IGV session file, not our own format.

**Comment by olegs** [comment]
Fixed as of https://github.com/JetBrains-Research/epigenome/commit/3d833508a7aabe66efd9497a08ddb7c86322d643
