### ISSUE TITLE
Add scale to BAM file coverage track

### ISSUE THREAD

**Issue by Xewar313** [JetBrains-Research/jbr#200]
Add scale to BAM track, similar to the one used by BigWig track
![image](https://github.com/JetBrains-Research/jbr/assets/69756491/80be8c24-1716-4128-bbb3-5492c11aded6)

**Comment by iromeo** [comment]
Instead of the word `Coverage` more useful is to make focus that for PE library we show 'Fragments' coverage and for SE library `Reads` coverage. I think word `Coverage` could be omitted. And also if track height is not big enough to show title it is ok not to show it at all
