### ISSUE TITLE
Windows UI issues

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/jbr#24]
[]. Open URL dialog size is single line height, not convenient for entering track urls
[x]. Open bigwig/bigbed/.. file mask usability on windows - some option is preselected (bigbed) and uses can't find their bigwig files

**Comment by olegs** [comment]
2. Open dialog uses "All supported file types" preselected mask now.

**Comment by olegs** [comment]
The second issue is not a problem anymore with Amazon Corrette JDK11. 
1-line textedit field is not that big problem, since it can be easily resized.

**Comment by iromeo** [comment]
> 1-sized
Our tutorial demonstrated that often users do not understand that it ‘can be easily resized’ and suffer with 1-line text fields.

**Comment by olegs** [comment]
Obsolete
