### ISSUE TITLE
Latest version of SPAN (1.5) is not supported?

### ISSUE THREAD

**Issue by AlePur** [JetBrains-Research/jbr#272]
I got a deserialization error when loading SPAN model generated with span 1.5.6, which was a bit confusing. I figured out that 1.5 is not supported and used the older 1.4 SPAN release which worked. I think newest version should be supported or it should be indicated that 1.5 is not working with jbr.

**Comment by olegs** [comment]
We are expecting to release a new, updated version of JBR in a couple of weeks.
It will contain lots of new features including SPAN 1.5+ models support.
