### ISSUE TITLE
JBR track legend anti-aliasing issue (Linux)

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/jbr#32]
Linux: UNITY (@dievsky env) + JB Runtime
![image](https://user-images.githubusercontent.com/72933/41535869-8442d8c4-730c-11e8-8d98-fd7d3ace4876.png)

Seems anti-aliasing not enabled for text in track views, but is ok in scollpane header. Or maybe fonts are different

**Comment by olegs** [comment]
Obsolete, as of 1.0.beta.4787.
