### ISSUE TITLE
High DPI display support [windows]

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/jbr#35]
Fonts don't look nice: probably due to anti aliasing usues or lack of high dpi.
Monitor: Dell UltraSharp U2410, 1920x1200

![image](https://user-images.githubusercontent.com/72933/38410234-b8c1f832-398c-11e8-9103-08b3ecc41758.png)

- [x] Default JLabel().font is a bit better than sansserif (but on Linux default JLabel font is bold, looks not very good)
- [x] JetBrains JRE is required for high DPI display support for windows
- [ ] Update src to support JB RE high DPI api

**Comment by olegs** [comment]
Fixed resently together with #101

**Comment by iromeo** [comment]
Related commit: https://github.com/JetBrains-Research/epigenome/commit/1994acefe71d6547f02d44c52b952881352409c4
