### ISSUE TITLE
JBR - cannot open SICER results without any extension

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/jbr#52]
SICER without input yields result file without any extension.
Open BED files action should allow to pick any file.

**Comment by dievsky** [comment]
Does it? I thought SICER no-control peaks were `.scoreisland`.

**Comment by olegs** [comment]
Well I am not 100% sure, however one of my students had some issue with this. 
Probably allowing to use any file type will help in corner cases.

**Comment by iromeo** [comment]
Is duplicate of https://github.com/JetBrains-Research/jbr/issues/53

P.S:
> Does it? I thought SICER no-control peaks were .scoreisland.

Correct, see https://github.com/JetBrains-Research/washu/issues/27#issuecomment-440221381

> Well I am not 100% sure, however one of my students had some issue with this.

The issue is for "with control" case.
