### ISSUE TITLE
JBR Cannot load "SICER + control" output files due to lack of file extension

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/jbr#53]
Example

`test-W200-G600-islands-summary-FDR.01`: summary file of significant islands with requirement of FDR=0.01. It has the format:
chrom, start, end, ChIP_island_read_count, CONTROL_island_read_count, p_value, fold_change,

see https://github.com/JetBrains-Research/washu/issues/27

Most likely JBR has difficulty loading this files due to lack of file extension

**Comment by iromeo** [comment]
@olegs Please clarify, does "Open from URL" should also open any unrecognized file as BED one?

**Comment by olegs** [comment]
I think it should NOT. Omitting file extension should be allowed only in case when loading from dialog.

**Comment by iromeo** [comment]
I'm not sure, that making any file selectable in Load Bed file dialog is user-friendly. So we could
1) Remove all masks and leave just any file (*.*)
2) Enable (*.*) mask in "Load Bed File" dialog but leave all supported files extensions as a default choice.

The difference will be visible only on Linux, Windows

**Comment by dievsky** [comment]
Most Windows programs offer "All files" as the last option in the file type selector, I think. We could do just the same, so option 2.
