### ISSUE TITLE
Open session doesn't scale up track sizes in case of using big fonts

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/jbr#54]

**Comment by olegs** [comment]
Screenshot after loading session http://artyomovlab.wustl.edu/publications/supp_materials/4Oleg/2019_sc_ATAC_seq_gxfer1_39174753087306/session.yaml
<img width="504" alt="Screenshot 2019-03-26 at 17 04 17" src="https://user-images.githubusercontent.com/75644/55003305-3663df80-4fe9-11e9-9916-f6ca8376af2a.png">

**Comment by iromeo** [comment]
Cannot reproduce in #4800

**Comment by iromeo** [comment]
Update: local sessions - ok, remote doesn't scale up

**Comment by iromeo** [comment]
P.S: Please add tests on scaling
