### ISSUE TITLE
Genes track view - gene names blinking

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/jbr#56]
Use BigFonts, open hg38 chr1:73092715-75676112.
<img width="1288" alt="Screenshot 2019-03-27 at 12 18 19" src="https://user-images.githubusercontent.com/75644/55064171-95c5fc00-508a-11e9-8eb3-7443fd99b571.png">
Press right button - and genes names are gone.
<img width="1287" alt="Screenshot 2019-03-27 at 12 18 33" src="https://user-images.githubusercontent.com/75644/55064226-a8d8cc00-508a-11e9-8400-7fb4ed49d793.png">

**Comment by iromeo** [comment]
They are show only if enough space

**Comment by olegs** [comment]
Don't see any reasons to hide ERICH3 gene name in second case.

**Comment by iromeo** [comment]
@olegs what does `invalid` tag means here? is an issue is invalid and could be closed or it is a synonym to `bug` ?

**Comment by iromeo** [comment]
> Don't see any reasons to hide ERICH3 gene name in the second case.
Could you point where do you expect to see these labels? 

I still sure that there is not enough space for the label on the screenshot, don't forget that label is shown near 5' end.

**Comment by olegs** [comment]
There are lot of genes on the second case, where there is plenty of space to fit gene name.

**Comment by iromeo** [comment]
The space is on the wrong end of gene

**Comment by iromeo** [comment]
And "AC133865.1" disappears if scroll right from `chr1:72963855-75547252`
![image](https://user-images.githubusercontent.com/72933/55068786-ae86df80-5093-11e9-9e45-e74628361209.png)
to `chr1:72996059-75579456`
![image](https://user-images.githubusercontent.com/72933/55068839-c8c0bd80-5093-11e9-8517-6e40d361ee1d.png)

**Comment by iromeo** [comment]
Fixed
