### ISSUE TITLE
About handler doesn't work in JB Runtime 11 (MacOS)

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/jbr#58]
Native about menu handler doesn't work on MacOS using JetBrains 11 runtime (jbr-11_0_2-osx-x64-b157).

**Comment by iromeo** [comment]
As a workaround "About" is shown in `Help` menu as in Windows/Linux

**Comment by olegs** [comment]
Works fine on Amazon Corretto JDK11.

**Comment by iromeo** [comment]
You mean native "About" menu, like below?
![image](https://user-images.githubusercontent.com/72933/79117716-8cdac200-7d94-11ea-9d4d-a7ad646d6d39.png)

**Comment by olegs** [comment]
Obsolete as we use Corretto JDK, see e059f63eaa4966a3322ae495ecf9c8d72b134f63
