### ISSUE TITLE
JBR should show information about scales for BED tracks (probably in legend)

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/jbr#63]
At the moment we use 80 percentile scaling of score instead of converting it to alpha in 0-1000 using.

**Comment by dievsky** [comment]
> instead of converting it to alpha in 0-1000

That's probably because literally no one respects the 0-1000 limits. :))

**Comment by olegs** [comment]
Having autoscale option by default is great here, however if you deal with a group of tracks, sometimes it can be useful to hard limit max scale.

**Comment by dievsky** [comment]
We could make a legend like "15- // colour gradient bar with alpha changing from the lowest to the highest setting // 100+". Maybe without - and +.

**Comment by dievsky** [comment]
@olegs You can select the group and set Scales Max for them. But you're right that we normally don't know which limit to set, since we don't know what score corresponds to which alpha.

**Comment by olegs** [comment]
Yes, the issue is just about explicitly demonstrating the default scale.

**Comment by dievsky** [comment]
Current state of implementation (jbr-issue-63 branch):
- the score-as-alpha legend appears only if there's no other legend, if score-as-alpha is enabled and if the score isn't constant;
- the legend is always shown in the track's default colour, regardless of the actual colour mode (fixed or region RGB).
What should be done next:
- the legend should probably be replicated for filtered BED tracks;
- rendering tests should be added.

**Comment by dievsky** [comment]
The legend now works for filtered BED tracks.
Also, issue #66 has been identified while working on this.

**Comment by dievsky** [comment]
Closing, since the PR linked above has been merged.
