### ISSUE TITLE
Cannot load track 

### ISSUE THREAD

**Issue by DaryaChaplygina** [JetBrains-Research/jbr#65]
Error occurred while loading SICER output track. Here is the screenshot and log file:
 
![Screenshot_20190428_210453](https://user-images.githubusercontent.com/17967984/56868397-ac999e80-69fa-11e9-9ea3-42d3cb4b9883.png)

**[jbr.log](https://github.com/JetBrains-Research/jbr/files/3125323/jbr.log)**

**Comment by olegs** [comment]
Darya, could you please open this file once again and attach the log file?  It can be found using menu option  "JBR | Help | Open in finder".
Also while creating bug reports it will be good to mention the version of JBR.

**Comment by dievsky** [comment]
It looks like the usual problem with SICER not respecting the 0-1000 score limit.

**Comment by olegs** [comment]
Actually even MACS2 in its documentation claims the following: "Please note that currently this value might be out of the [0-1000] range defined in UCSC Encode narrowPeak format"
See https://github.com/taoliu/MACS

**Comment by dievsky** [comment]
So, after just 19 days, we are ready to give a statement on the reported issue!
The currently released version of JBR tries to read BED files according to the standard published by UCSC. Among other things, UCSC states that the BED score is an integer in range 0..1000. However, MACS2, SICER and many other BED providers do not respect this standard. This leads to errors when JBR encounters scores that are too high. Unfortunately, there's no way to make the current version of JBR load this particular BED file (the only way is to edit the file in one way or another).
Good news, however: the upcoming release should fix this problem.

**Comment by dievsky** [comment]
The version released on May 17 should fix this issue. Please feel free to reopen if the problem persists!
