### ISSUE TITLE
Score column switching sometimes leads to empty track

### ISSUE THREAD

**Issue by dievsky** [JetBrains-Research/jbr#69]
About 1 time in 10 (a very approximate value), switching the score column in UI leads to one or more of BED tracks losing all locations.

![vanishing_track](https://user-images.githubusercontent.com/1926074/57523475-5e9f6780-7325-11e9-8b15-24370659fcac.png)

As far as I was able to determine, this is caused by CancellationException being thrown (and silently swallowed) after a cancellation state check fails. Unfortunately, my expertise in cancellation states proved insufficient to understand what cancels the task and why. That's why I'm requesting @iromeo 's help.

Steps to reproduce:
1. open JBR;
2. load a few scored BED files (MACS2 peaks should do);
3. switch the score column from the context menu a few times.

**Comment by iromeo** [comment]
@dievsky Rendering tasks canceled when user has decided to switch to another location, e.g. fast scrolling, etc.

**Comment by iromeo** [comment]
```
 override fun initConfig(model: SingleLocationBrowserModel, renderingContext: RenderingContext) {
        super.initConfig(model, renderingContext)
        synchronized(this) {
            val actualScoreColumn = get(SCORE_COLUMN)
            if (actualScoreColumn != renderedScoreColumn) {

                // XXX: in case of errors due to inconsistent in paint consider
                // packing all necessary stuff to renderingContext[TRACK_DATA] and extract it in
                // paint method

                rebuildScores(model.genomeQuery, CancellableState.current(), renderingContext)
                renderedScoreColumn = actualScoreColumn
            }
        }
    }
```

* Here isn't very good to use 'synchronize' all background async rendering calls
* Also `get(SCORE_COLUMN)` is being changed in EDT ( AWT event dispatch thread), so synchronization here will pause async rendering events, but score column could be changed in EDT while `rebuildScore` is being calculated this will result in different runtime bugs inside rebuildScore

**Comment by dievsky** [comment]
@iromeo There's no location switch happening in the described scenario. At least, not one initiated by the user (me).

**Comment by iromeo** [comment]
@dievsky ```
if (BedField.ITEM_RGB !in get(BED_FORMAT)) {
            LOG.info("${bedSource.presentablePath()} doesn't provide item RGB field, color mode changed to FIXED.")
            set(LAT_COLOR_MODE, ColorMode.FIXED)
        }
```
this code could fire additional repaint event, see `LocationAwareTrackView.init()`

**Comment by iromeo** [comment]
@dievsky Also you've launch `preprocess` method from `initConfig`. Preprocess is cancelable for the case when a user wants to stop track loading. `initConfig` could be canceled when rendering event is out-of-date. It is done silently because it is a normal case, we cancel all legacy events. In our case such legacy rendering occupies "synchronize" section, calls preprocess, fails at some point, but `rebuildScores` overrides `preprocess` impl overrides `location`, `names`, `scores`, `colors` maps with empty values, thus you get empty track. Also 'preprocess' method updates `renderedScoreColum` field, so all newer rendering events considers that column is up-to-date. 

The bug is due to bugs in how column changes is implemented in case of multithreaded execution.

**Comment by iromeo** [comment]
@dievsky Could you implement `rebuildScore` in BedLocationsTrackView similar to `FilteredBedTrackView` and `BigBedTrackView` ?

**Comment by dievsky** [comment]
In a personal Slack discussion, @iromeo has confirmed that he already made the necessary edits.

**Comment by iromeo** [comment]
See commit https://github.com/JetBrains-Research/epigenome/commit/2cfbc50c0cdbd7b0842c9af5e3b4f41391c3b44d, (commit message is incorrect due to some bug during remote test run & commit action).
