### ISSUE TITLE
BED tracks don't get repainted of Region Label change.

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/jbr#79]

**Comment by dievsky** [comment]
And on Region Score Column change. And seemingly on any other change except changing the viewport. It's most likely due to the "selection shouldn't trigger repaint" clause in `TrackViewRenderComponent#repaintRequired`.

**Comment by iromeo** [comment]
@olegs How to reproduce? I've tried latest release, opened BED track, zoom into a peak, select from context menu "region label | score" and noticed that peak label has changed.

**Comment by dievsky** [comment]
The latest release was on May 17, while this issue is from July 9, and the changes that had likely introduced this bug were pushed on July 7.

**Comment by olegs** [comment]
Fixed with https://github.com/JetBrains-Research/epigenome/issues/1439
