### ISSUE TITLE
Track About Table column names not readable

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/jbr#80]
See screenshot:
![2019-07-28_11-39-54](https://user-images.githubusercontent.com/72933/62004502-b3859980-b12e-11e9-8584-92b59a374f87.png)

It's hard to figure out the meaning of numbers in the table. So we cannot quickly go through the stats and have to export table in *.tsv file (copying table and opening in some spreed sheet app also isn't very convenient for quick look and doesn't copy column names).

Desired behaviour: table is wide and wrapped in scroll pane, all columns width is set according column header width.

**Comment by olegs** [comment]
Fixed in https://github.com/JetBrains-Research/epigenome/commit/4ebb4bcb0101451147fea3fb4b75f622d649e47a
