### ISSUE TITLE
Support for vector screenshots

### ISSUE THREAD

**Issue by assaron** [JetBrains-Research/jbr#9]
So that one can use JBR for making publication quality figures

**Comment by olegs** [comment]
Actually if you have a look at the structure of SVG created by IGV, the whole picture is in vector format, but the tracks themselves are in raster format. So that they cheat a little bit. 
@assaron Do you think we should use the same approach or have everything in vector format?

**Comment by assaron** [comment]
Even that would be great, I think. I like IGV one enough, because there in vector you can easily remove elements which are not needed and move them around. Also, only the coverage tracks seems to be rasterized: genes and beds are vector.

**Comment by olegs** [comment]
Will be available in next release.
