### ISSUE TITLE
ENCODE project search

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/jbr#91]
Save search window position / size.

**Comment by dievsky** [comment]
Do you mean "save them across JBR launches"? If you close and reopen the dialog itself (but not the browser), it should already appear the same.

**Comment by dievsky** [comment]
I think we don't currently save any comparable information. We could save it in a dedicated `yaml` file in `.jbr_browser` folder.

**Comment by dievsky** [comment]
Dialog size and position saving implemented. A preference saving bug #93 was identified and fixed along the way.
