### ISSUE TITLE
File entries with same names in ENCODE search results

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/jbr#95]
* Open 'gsm1102785', hg19
![image](https://user-images.githubusercontent.com/72933/74544125-abb90580-4f57-11ea-8909-ab705a5f2443.png)

Here 4 'peaks' tracks are shown. It is hard to understand what is the difference, so we have to click on each file in order to view details at the ENCODE site.

Could we show some additional information? E.g.
* ENCODE tags some of this peaks as "bed broadPeak", other "bed narrowPeak" file format
![image](https://user-images.githubusercontent.com/72933/74544365-0eaa9c80-4f58-11ea-87c3-7a3cd5ac99ae.png)

* Also by ID it isn't clear what is inside, e.g. 'Original filename' show that it is actually H3K27me3 (see https://www.encodeproject.org/files/ENCFF120REH/)

We could show some useful info in a popup, e.g submission date, project name, original file name, etc.

**Comment by iromeo** [comment]
E.g. in IGV results look like:
![image](https://user-images.githubusercontent.com/72933/74546766-284de300-4f5c-11ea-8d5f-4165903d1827.png)

**Comment by dievsky** [comment]
Sounds good!
Notes to self: `narrowPeak` information is stored in `file_format_type` field; we also should show the contents of `biological_replicates` and `technical_replicates` list fields.

**Comment by dievsky** [comment]
Alternatively, we can just use `file_type` instead of `file_format` and `file_format_type`.

**Comment by dievsky** [comment]
I've added the discussed information, but now the output is not easily readable.

Maybe we do need to drop the experiment / file hierarchy and change to a table view.
Or maybe we could just use a custom tree cell renderer to align the fields, like we do with experiments.

![tmi170220](https://user-images.githubusercontent.com/1926074/74653618-da69f280-5188-11ea-83a3-585cfd997fdc.png)

**Comment by dievsky** [comment]
This could work, I think:
![jtraoi170220](https://user-images.githubusercontent.com/1926074/74663577-53bf1080-519c-11ea-8fd8-46b4601f1272.png)

(I'll probably add an ability to sort files on top of that.)

**Comment by iromeo** [comment]
I like 2nd version more. 

> (I'll probably add an ability to sort files on top of that.)
Still not sure whether it is easier than replacing the whole component with a table, but we could try.

**Comment by dievsky** [comment]
Made file info fields aligned, added a sort header.

**Comment by dievsky** [comment]
We could also implement an on-hover popup with even more info.

**Comment by dievsky** [comment]
Switched to table view with 11 columns of data. Should be enough to distinguish between all the files now.

**Comment by olegs** [comment]
Closing as obsolete. All possible information is available in the table view.
