### ISSUE TITLE
Show cell typel/hist modification information when search by ENCODE/GEO id

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/jbr#96]
It isn't clear what is here
![image](https://user-images.githubusercontent.com/72933/74544125-abb90580-4f57-11ea-8909-ab705a5f2443.png)

E.g. I could make a typo when typing an ENCODE file ID, so it will be good to see what is this data about. Is it expected cell type and histone modification or not.

Here results look ok here
![image](https://user-images.githubusercontent.com/72933/74544936-0d2da400-4f59-11ea-8f47-0f3126f20cd7.png)

**Comment by dievsky** [comment]
Well, sadly, we can't control whether the experiment's author provided a description.

We can, however, attempt to parse `target` field and incorporate that info in the representation.

**Comment by iromeo** [comment]
> Well, sadly, we can't control whether the experiment's author provided a description.
Sorry, I don't get the point. AFAIU if we search experiment by histone modification name we show detailed info (see 2nd screenshot) if we do a similar search for known ENCODE/GEO id we don't show target, etc info. I believe that we could show target, cell type info because it is shown at https://www.encodeproject.org/experiments/ENCSR080XUB/.

**Comment by dievsky** [comment]
Actually, we show the description if it's present, and the experiment ID otherwise. It doesn't matter what the search term was.
We could replace the ID with some synthetic description assembled from metadata.

**Comment by iromeo** [comment]
In IGV it looks quite convenient ![image](https://user-images.githubusercontent.com/72933/74546766-284de300-4f5c-11ea-8d5f-4165903d1827.png) all key information is there. I expect to see some similar info here. Not sure whether we need to duplicate info for each item (like in IGV) or show it once in node caption.

I like IGV's table representation because we could sort by columns. I think it might be convenient when you have multiple results.

**Comment by dievsky** [comment]
Mixing tables and trees sounds messy, to be honest. Maybe we need to ax the tree approach completely and replace it with a table.

**Comment by iromeo** [comment]
Yes, I agree that mixing trees and tables is messy. I meant switching to tables instead or carefully think on a usability of trees approach.

**Comment by dievsky** [comment]
Switch to table view is complete. Cell type / target / assay information is displayed (and can be sorted / filtered against).

**Comment by olegs** [comment]
Closing as obsolete.
