### ISSUE TITLE
ENCODE search cannot find ChromHMM tracks

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/jbr#98]
It will be convenient to add ChromHMM BigBed tracks, but search cannot find anything for  https://www.encodeproject.org/annotations/ENCSR511WOF/ track
Genome: `hg19` 
![image](https://user-images.githubusercontent.com/72933/74546988-7367f600-4f5c-11ea-929c-e6ef5b9ca54b.png)

![image](https://user-images.githubusercontent.com/72933/74547038-87abf300-4f5c-11ea-9a54-03b24edfbb12.png)

**Comment by dievsky** [comment]
Hmm, that can be a problem. We currently can search only for experiments, and the ChromHMM files don't seem to have an associated experiment.

**Comment by iromeo** [comment]
The search field at ENCODE web pages is able to find them (https://www.encodeproject.org/search/?searchTerm=chromhmm). Seems it is quite reasonable to have similar behavior.

**Comment by iromeo** [comment]
P.S: IGV also fails to find it

**Comment by dievsky** [comment]
So, in general, we probably want to show filesets / datasets (no idea what's the difference) along with the experiments. That shouldn't be hard to arrange. But, plot twist, that particular fileset won't show because it's missing assembly annotation. Luckily, there are enough ChromHMM filesets with correctly specified assembly.

**Comment by iromeo** [comment]
Seems it is 'dataset' and has `files` for `hg19` genome (https://www.encodeproject.org/files/ENCFF122PDV/)
![image](https://user-images.githubusercontent.com/72933/74647396-9f69be00-518c-11ea-9985-6e6cc465b152.png)

**Comment by iromeo** [comment]
Maybe datasets don't specify genome build field and can contain files with different assemblies

![image](https://user-images.githubusercontent.com/72933/74647715-3a629800-518d-11ea-9b26-c64a4b3e1a64.png)

**Comment by dievsky** [comment]
Actually, "good" filesets / datasets do have assembly specified, as evidenced by these search results: https://www.encodeproject.org/search/?searchTerm=chromhmm&assembly=hg19 .

**Comment by iromeo** [comment]
Seems our favourite CD14 chromhmm isn’t good enough

**Comment by dievsky** [comment]
Our favourite ChromHMM is also totally deprecated by ENCODE. :)) It doesn't contains a single non-deprecated file. In short, I see no compelling reason to make the plugin work in such way as to include it.

The plugin now searches for annotations in addition to experiments. Search for `chromhmm` now returns results.

**Comment by iromeo** [comment]
AFAIU all `hg19` is deprecated in Encode

**Comment by iromeo** [comment]
I've just checked it, nice to see chromhmm results there. 

Is it possible to figure out cell type and how much states there? In the current version, all results look same

![image](https://user-images.githubusercontent.com/72933/74766270-19399e80-5296-11ea-9ccc-35d46624fea9.png)

**Comment by olegs** [comment]
Current layout is something that blows my mind. Can we have this organised in a simple table?

**Comment by dievsky** [comment]
@iromeo :
> AFAIU all hg19 is deprecated in Encode

Not at all, see https://www.encodeproject.org/annotations/ENCSR797XOC/ . All its `hg19` files are `released`.

**Comment by dievsky** [comment]
@olegs Well, it depends on how much we are willing to sacrifice the current hierarchy. With a table, you can't have the expand / collapse mechanics that we currently use to hide the hundreds of files under a dozen of experiments. We could drop the hierarchy, search for files directly and display them in a table, if you think that's a better approach.

**Comment by dievsky** [comment]
Following the personal discussion, we've decided to use ENCODE search to search for experiments and annotations, retrieve the list of files from the results, then query and display all the files in the table.
Another technical problem arose: searching for `H3K4me1`, for example, yields about 9K files. This translates to 9K HTTP GET queries to procure the file metainfo. Kotlin coroutines deal with this problem valiantly, but most of the requests are killed by socket timeout. It's likely that ENCODE starts throttling them at some point.

**Comment by iromeo** [comment]
@dievsky What timeout do you use between sequential requests? Is it almost 0 ms or not?

**Comment by dievsky** [comment]
@iromeo yes, but this is not really relevant. Even without any timeout, 9K requests will take at least 15 minutes, which is not realistic by any standard. I actually seem to have managed to implement option 3.

**Comment by olegs** [comment]
Can you please describe the way you implemented the option 3 in more detail?

**Comment by dievsky** [comment]
When the user hits "Search", we do a `search` query with `type=Experiment` and `frame=embedded`, which fetches almost all necessary info in one colossal query. (Once I wrangle `ktor` into submission, the response will be gzipped, significantly reducing the transfer time.) After the results arrive, we do several additional queries to translate the few missing pieces of information (like cell type, which the main query returns only as an ID).

**Comment by dievsky** [comment]
`gzip` is working, though it currently requires a pretty nasty hack because of [a bug in ktor](https://github.com/ktorio/ktor/issues/1189). Hopefully, we'll be able to remove the hack after the next ktor release.

Searching for "monocyte":
![encode260220](https://user-images.githubusercontent.com/1926074/75344162-4ab7f880-589a-11ea-8cc8-c7936e6cb198.png)

Searching for "chromhmm":
![encode_chromhmm260220](https://user-images.githubusercontent.com/1926074/75344188-5d323200-589a-11ea-8b0f-c4827240357e.png)

Alternative assembly suggestions:
![encode_alt260220](https://user-images.githubusercontent.com/1926074/75344248-8c48a380-589a-11ea-848e-7fccfb7323b1.png)

**Comment by dievsky** [comment]
The file table is sortable by clicking on a column header and supports the file type filtering using checkboxes:
![encode_checkbox260220](https://user-images.githubusercontent.com/1926074/75344386-d2056c00-589a-11ea-9a0e-01dc22ab76e0.png)

**Comment by dievsky** [comment]
A reasonably general query (like "monocyte") takes about 15 seconds to complete. Subsequent queries are somewhat faster because we cache the cell types and targets.

**Comment by olegs** [comment]
`View Details` now sounds a little bit awkward, since we see a lot of information, maybe `Web Description`?

**Comment by iromeo** [comment]
> The file table is sortable by clicking on a column header and supports the file type filtering using checkboxes:

Still cannot select `narrowPeaks`, I'll get multiple tracks with different `bed` file per sample. Could we build filters from data instead of several hardcoded values, e.g.:
* one column - one filter
* filter allows to select one or several values from the list of unique values (e.g. if file types are "bed", "narrowPeak", "broadPeak", than we will able to select "narrowPeak")

**Comment by dievsky** [comment]
@olegs maybe `File Details` and a browser icon? "Web Description" is a really long name for a button.

**Comment by dievsky** [comment]
@iromeo Well, technically you can sort by the `file type` column and get all the `bed narrowPeak` in one place. (And `bigBed narrowPeak` also in one, though totally different, place.)
`narrowPeak` and `bed` are not different formats; the former is a subtype of the latter. More precisely, `file_type="bed narrowPeak", file_format="bed", file_format_type="narrowPeak"`. Similarly, we have `bigBed narrowPeak`, or `bed bed9` file format types.
We could replace the `file type` column with `file format` and `file format type`, and implement a drop-down filter for each column based on its values.

**Comment by dievsky** [comment]
@iromeo OK, ready. Right-click on a column name to bring up a filter checkbox popup menu. Click on a value to add to / remove from the filter, ctrl-click the value to filter everything else out.

**Comment by olegs** [comment]
CD14 chromhmm request finds nothing, but same request on website yields some results.
<img width="1279" alt="Screenshot 2020-02-27 at 13 24 39" src="https://user-images.githubusercontent.com/75644/75435732-87e8bd00-5964-11ea-9e52-5e0ee39c6f72.png">


<img width="415" alt="Screenshot 2020-02-27 at 13 23 30" src="https://user-images.githubusercontent.com/75644/75435661-6c7db200-5964-11ea-9713-84e079607562.png">

**Comment by dievsky** [comment]
Like we already discussed with @iromeo , these results are highly problematic:

![encode_no_files270220](https://user-images.githubusercontent.com/1926074/75436491-f4f45680-5954-11ea-9377-6632a7896645.png)

Note that little "no files to display" message. These file sets are also not annotated with any assembly, despite clearly belonging to `hg19`.

If we absolutely insist on seeing these, we can add another couple of queries to retrieve the file sets without an assembly.

**Comment by olegs** [comment]
It looks like the issue can be closed, or at least title should be changed. @dievsky ?

**Comment by dievsky** [comment]
Yes, the plugin certainly can find chromHMM tracks now.
